---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "ofddb"
  namespace: "default"
  labels:
    app001: "ofddb"
spec:
  replicas: 1
  selector:
    matchLabels:
      app001: "ofddb"
  template:
    metadata:
      labels:
        app001: "ofddb"
    spec:
      containers:
      - name: "ofddb-sha256-1"
        image: "gcr.io/charged-ground-326209/github.com/vidyashri928/ofddb@sha256:66cb5f568131ec7b38f68c9ad809697169fe76dd716dcdd918684e0ccf2d0067"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "ofddb-hpa-e6ij"
  namespace: "default"
  labels:
    app001: "ofddb"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "ofddb"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
